### ISSUE TITLE
Address is: Error Domain=kCLErrorDomain Code=2 "(null)"

### ISSUE THREAD

**Issue by blinvisible** [clburlison/pinpoint#22] opened 2016-11-23 19:07 UTC
I don't know if this is a change in pinpoint, a change in Apple's API or what, but all I get for reverse geocoding when LookupService is set to "apple" is the following:

`Address is: Error Domain=kCLErrorDomain Code=2 "(null)"`

I thought at first it might just be a temporary issue with Apple services but the problem has persisted for several months. It was occurring with pinpoint v1.0.0.77 and continues with v1.0.2.79.

Setting LookupService to 'google' returns the correct street address.

Debug output (with latitude/longitude redacted):
```
$ sudo pinpoint -fvv
[DEBUG]: Current LookupService is: apple
[INFO]: Location Services are enabled
[DEBUG]: Current location domain of client.plist is: 
[DEBUG]: {
    Authorized = 1;
    BundleId = "com.apple.locationd.executable-/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python";
    Executable = "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python";
    Hide = 0;
    LocationTimeStopped = "501619995.550967";
    Registered = "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python";
    Requirement = "cdhash H\"f77a66de9468d7b45045f9fa2f4ed5e4330863d8\" or cdhash H\"e8071e45cff63f1b3cf90ba010fea769aca77166\" or cdhash H\"4ee66de39dc92020e4d448664fd987795782ff54\" or cdhash H\"5ccab7b94f791e454aee9438ec5bf15c1a242a0b\"";
    Whitelisted = 0;
}
[INFO]: Python is enabled
[DEBUG]: Updating 'LastCheckDate' timestamp
[DEBUG]: Storing past location
[DEBUG]: Wireless interface is currently: On
[DEBUG]: No preflight script on disk
[DEBUG]: Running lookup loop: 0
[INFO]: Process a lookup request via: apple
[DEBUG]: Successful lookup request: [lat], [lon]
[INFO]: Process a lookup request via: apple
[DEBUG]: Successful lookup request: [lat], [lon]
[INFO]: Process a lookup request via: apple
[DEBUG]: Successful lookup request: [lat], [lon]
[INFO]: Process a lookup request via: apple
[DEBUG]: Successful lookup request: [lat], [lon]
[INFO]: Process a lookup request via: apple
[DEBUG]: Successful lookup request: [lat], [lon]
[INFO]: Process a lookup request via: apple
[DEBUG]: Successful lookup request: [lat], [lon]
[INFO]: Process a lookup request via: apple
[DEBUG]: Successful lookup request: [lat], [lon]
[INFO]: Process a lookup request via: apple
[DEBUG]: Successful lookup request: [lat], [lon]
[INFO]: Doing a reverse lookup via: apple
[INFO]: Address is: Error Domain=kCLErrorDomain Code=2 "(null)"
[DEBUG]: Writing current run details to: /Library/Application Support/pinpoint/location.plist
[INFO]: Current location: [lat], [lon]
[INFO]: Run status: Successful
[DEBUG]: No postflight script on disk
```

Happy to help debug or answer questions as needed. Thanks.

**Comment by clburlison** [comment] 2016-11-24 01:51
Thank you for the report. I will take a look at this and see if I can figure out what is happening.

**Comment by blimvisible** [comment] 2017-02-21 19:33
Some StackOverflow threads suggest this will happen if Apple's geocoder receives too many requests from a device within a short time period (more than one request per minute). One example:

[http://stackoverflow.com/questions/17867422/kclerrordomain-error-2-after-geocoding-repeatedly-with-clgeocoder](http://stackoverflow.com/questions/17867422/kclerrordomain-error-2-after-geocoding-repeatedly-with-clgeocoder)

**Comment by clburlison** [comment] 2017-02-28 23:29
Alright @blimvisible sorry, I've been bad at responding to this issue. I have been trying to resolve this but haven't made any progress. If I can not get this resolved in the next week or two I'll end up reverting the ReverseLookup to use the google api.

**Comment by kevinmcox** [comment] 2017-03-11 03:32
Not sure if this tidbit will be helpful or not, but after upgrading my MBP from 10.11.6 to 10.12.3 today, I'm getting an address where before I have only gotten this error.

The El Capitan machines with PinPoint installed are still displaying the error.

**Comment by blimvisible** [comment] 2017-03-13 14:30
I can also confirm that I am running OS X El Capitan 10.11.6 when I see that error.

**Comment by clburlison** [comment] 2017-03-15 16:26
Hey guys the 10.11 data point was something that I wasn't looking at. I just got a third report that they are getting the same error on 10.11 boxes. All of my tests have been on my personal 10.12 machine so that makes sense. 

My new guess is that this issue is actually in the PyObjC bridge for 10.11 but I won't be able to poke at that until next week to verify. Honestly if that is the case this might not be fixable on 10.11 or it isn't worth the time to make it work as you could revert to the google provider.

**Comment by clburlison** [comment] 2017-05-26 15:05
I'm going to go ahead and close this issue. The problem is with the pyobjc framework on 10.11. I might be able to manually patch the files in place for pinpoint but really you should be on 10.12 since 10.13 is going to be released soon.

If you have 10.11 machines and want to continue using pinpoint on them I recommend changing the `AddressLookupService` key to the google api via https://github.com/clburlison/pinpoint/wiki/Preferences

**Closed by clburlison** 2017-05-26 15:05 UTC
Labels: bug

**Comment by blinvisible** [comment] 2017-05-30 13:52
Makes sense. Thanks for your continued work on pinpoint!
