### ISSUE TITLE
Intermittent failures with munkireport

### ISSUE THREAD

**Issue by ofirgalcon** [clburlison/pinpoint#40] opened 2018-03-14 23:42 UTC
I'm finding that on many of my clients pinpoint/location fails with an error, even on first run. But many times it runs once successfully and reports a stale location thereafter.

Error obtaining a location. LS was unresponsive or a lookup timeout occurred.

I ran pinpoint -f on a few clients, it found a new location and that appeared in MR after I ran managedsoftwareupdate

**Comment by ofirgalcon** [comment] 2018-03-17 04:00
More info, in log I see this repeatedly

`2018-03-17 02:31:07 AM [INFO]: Python is enabled
2018-03-17 02:31:07 AM [DEBUG]: Updating 'LastCheckDate' timestamp
2018-03-17 02:31:07 AM [DEBUG]: Storing past location
2018-03-17 02:31:07 AM [DEBUG]: Wireless interface is currently: On
2018-03-17 02:31:07 AM [DEBUG]: No preflight script on disk
2018-03-17 02:31:07 AM [DEBUG]: Running lookup loop: 0
2018-03-17 02:31:12 AM [DEBUG]: Running lookup loop: 1
2018-03-17 02:31:22 AM [DEBUG]: Running lookup loop: 2
2018-03-17 02:31:37 AM [INFO]: Doing a reverse lookup via: apple
2018-03-17 02:31:37 AM [WARNING]: Unable to determine address
2018-03-17 02:31:37 AM [INFO]: Address is: Unable to determine address
2018-03-17 02:31:37 AM [WARNING]: Error obtaining a location. LS was unresponsive or a lookup timeout occurred.
2018-03-17 02:31:37 AM [DEBUG]: Keep past location as we were unable to determine your current location
2018-03-17 02:31:37 AM [DEBUG]: Writing current run details to: /Library/Application Support/pinpoint/location.plist
2018-03-17 02:31:37 AM [DEBUG]: No postflight script on disk
2018-03-17 02:45:00 AM [DEBUG]: Current LookupService is: apple
2018-03-17 02:45:00 AM [INFO]: Location Services are enabled
2018-03-17 02:45:00 AM [DEBUG]: Current location domain of client.plist is: 
2018-03-17 02:45:00 AM [DEBUG]: {
    Authorized = 1;
    BundleId = "org.python.python";
    BundlePath = "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app";
    Executable = "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python";
    Hide = 0;
    LocationTimeStopped = "542769032.793025";
    ReceivingLocationInformationTimeStopped = "542769004.8336639";
    Registered = "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python";
    Requirement = "identifier \"org.python.python\" and anchor apple";
    Whitelisted = 0;
}
`
However, if I run pinpoint -fvv I get the correct location:

`[INFO]: Location Services are enabled
[INFO]: Python is enabled
[INFO]: Process a lookup request via: apple
[INFO]: Process a lookup request via: apple
[INFO]: Process a lookup request via: apple
[INFO]: Doing a reverse lookup via: apple
[INFO]: Address is: xxxxx
[INFO]: Current location: xxxxxx
[INFO]: Run status: Successful
`

**Comment by clburlison** [comment] 2018-03-21 23:17
@ofirgalcon Thank you for the report. This is a duplicate of #31, as such I'll be keeping discussion regarding this bug in that issue.

**Closed as completed by clburlison** 2018-03-21 23:17 UTC
Labels: duplicate
